import { UserPath } from "shared/enum";

export const USER_NAMES: { [key in UserPath]: string } = {
  [UserPath.Default]: "Дорогие гости!",
  [UserPath.Dariga]: "Тетя Дарига",
  [UserPath.IslamKulyash]: "Дядя Ислям и Тетя Куляш",
  [UserPath.Halima]: "Тетя Халима",
  [UserPath.Nagima]: "Тетя Нагима",
  [UserPath.Damelya]: "Тетя Дамеля",
  [UserPath.Kamilya]: "Тетя Камиля",
  [UserPath.Ayman]: "Тетя Айман",
  [UserPath.KayratGulmira]: "Кайрат и Гульмира",
  [UserPath.Gayhar]: "Гаухар",
  [UserPath.ZhandosLuiza]: "Жандос и Луиза",
  [UserPath.ZhenisAygul]: "Женис и Айгуль",
  [UserPath.ErkenMadina]: "Еркен и Мадина",
  [UserPath.Gulzahira]: "Гульзахира",
  [UserPath.Mirash]: "Мираш",
  [UserPath.SerikGulya]: "Серик и Гуля",
  [UserPath.DidarAlia]: "Дидар и Алия",
  [UserPath.BahitzhanAyman]: "Бахытжан и Айман",
  [UserPath.SerikBayan]: "Серик и Баян",
  [UserPath.Roza]: "Роза",
  [UserPath.KazikanBizhan]: "Казикан и Бижан",
  [UserPath.ErlanDinara]: "Ерлан и Динара",
  [UserPath.AnatoliiElena]: "Анатолий и Елена",
  [UserPath.AlbertOlga]: "Альберт и Ольга",
  [UserPath.AlexandrIrina]: "Александр и Ирина",
  [UserPath.AlexandrElena]: "Александр и Елена",
  [UserPath.AbaySandugash]: "Абай и Сандугаш",
  [UserPath.VitaliiNadezhda]: "Виталий и Надежда",
  [UserPath.SergeyAnastasiya]: "Сергей и Анастасия",
  [UserPath.AndreyKsenia]: "Андрей и Ксения",
  [UserPath.EvgeniiAnna]: "Евгений и Анна",
  [UserPath.VictorOlga]: "Виктор и Ольга",
  [UserPath.NurzhanAynura]: "Нуржан и Айнура",
  [UserPath.ZharmanZhulduzMarat]: "Жарман, Жулдыз и Марат",
  [UserPath.EvgeniiAlina]: "Евгений и Алина",
  [UserPath.RuslanKorinna]: "Руслан и Коринна",
  [UserPath.NurlanDamelya]: "Нурлан и Дамеля",
  [UserPath.Diana]: "Диана",
  [UserPath.SerikKarligash]: "Серик и Карлыгаш",
  [UserPath.SandugashErik]: "Сандугаш и Ерик",
  [UserPath.OrkenAliya]: "Оркен и Алия",
  [UserPath.BolatAygul]: "Болат и Айгуль",
  [UserPath.ZhaslanZhazira]: "Жаслан и Жазира",
  [UserPath.UlanBayan]: "Улан и Баян",
  [UserPath.SergeiDiana]: "Сергей и Диана",
  [UserPath.TatyanaAdelia]: "Татьяна и Аделия",
  [UserPath.DmitriiZarina]: "Дмитрий и Зарина",
  [UserPath.EvgeniiSvetlana]: "Евгений и Светлана",
  [UserPath.OlegTatyana]: "Олег и Татьяна",
  [UserPath.ElenaLenar]: "Елена и Ленар",
  [UserPath.Talap]: "Талап",
  [UserPath.TimurNargiz]: "Тимур и Наргиз",
  [UserPath.DanialKristina]: "Даниял и Кристина",
  [UserPath.LayraAlbinaAdilTemirlan]: "Лаура, Альбина, Адиль, Темирлан",
  [UserPath.NyrkenAlina]: "Нуркен и Алина",
  [UserPath.SaniaMirasAmina]: "Сания, Мирас и Амина",
  [UserPath.BeybitAydana]: "Бейбит и Айдана",
  [UserPath.RuslanAynura]: "Руслан и Айнура",
  [UserPath.VyacheslavVadim]: "Вячеслав и Вадим",
  [UserPath.IlyasAysha]: "Ильяс и Айша",
  [UserPath.RobertEvgenia]: "Роберт и Евгения",
  [UserPath.NikolayLidia]: "Николай и Лидия",
  [UserPath.AntonAnastasia]: "Антон и Анастасия",
  [UserPath.PavelInnesa]: "Павел и Инесса",
  [UserPath.Asel]: "Асель",
  [UserPath.MuratAsel]: "Мурат и Асель",
  [UserPath.Aydar]: "Айдар",
  [UserPath.DostanGulmira]: "Достан и Гульмира",
  [UserPath.VyacheslaKristina]: "Вячеслав и Кристина",
  [UserPath.ShavkatGayhar]: "Шавкат и Гаухар",
  [UserPath.SerikNatalya]: "Серик и Наталья",
  [UserPath.Aznaur]: "Азнаур",
  [UserPath.Emir]: "Эмир",
  [UserPath.Angelina]: "Ангелина",
  [UserPath.Aysel]: "Айсель",
  [UserPath.Maria]: "Мария",
  [UserPath.Irina]: "Ирина",
  [UserPath.VladimirEkaterina]: "Владимир и Катя",
  [UserPath.Anton]: "Антон",
  [UserPath.Darya]: "Дарья",
  [UserPath.Azad]: "Азад",
  [UserPath.TimurAlexandra]: "Тимур и Александра",
  [UserPath.SergeiEkaterina]: "Сергей и Екатерина",
  [UserPath.AnastasiaIrina]: "Анастасия и Ирина",
  [UserPath.Georgii]: "Георгий",
  [UserPath.RustamAlina]: "Рустам и Алина",
  [UserPath.SvetlanaGalina]: "Светлана и Галина",
  [UserPath.AndreiMarina]: "Андрей и Марина",
  [UserPath.VladimirAnzhelika]: "Владимир и Анжелика",
  [UserPath.Nasiba]: "Насиба",
};
